#!/bin/bash

# Bail out if there's an error, or if any variables are undefined
set -eu

# Determine the path to this script, regardless of current working dir
scriptdir="$(dirname "$(readlink -f "$0")")"

source /home/sandboxes/kpurcell/repos/gbtgridder/gbtgridder/src/gbtgridder-venv-3.8.5/bin/activate
python ${scriptdir}/gbtgridder_matrix3_8.py "$@"

